version: '3' # specify docker-compose version

# Define the services/containers to be run
services:
  angular: # name of the first service
    image: docker-node-express-mongoapp
    build: ./AngularApp # specify the directory of the Dockerfile
    command: ng serve --host 0.0.0.0 --port 4200
    ports:
      - "4200:4200" # specify port forewarding
    volumes:
      - ./AngularApp:/usr/src/app
      - /usr/src/app/node_modules
    
 

  express: #name of the second service
    build: ./Nodejs # specify the directory of the Dockerfile
    ports:
      - "3000:3000" #specify ports forewarding

    command: node index.js

    volumes:
      - ./Nodejs:/usr/src/app
      - /usr/src/app/node_modules

    depends_on:
      - "database"

  database: # name of the third service
    image: mongo # specify image to build container from
    ports:
      - "27017:27017" # specify port forewarding
  